[package]
name = "adventofcode2023"
version = "0.1.0"
edition = "2021"
authors= ["Emiel Van Severen <emiel@vanseveren.dev>"]

[dependencies]
bstr = "1.8.0"
itertools = "0.12.0"
lazy_static = "1.4.0"
num = "0.4.1"
