[package]
name = "adventofcode2022"
version = "0.1.0"
edition = "2021"
authors= ["Emiel Van Severen <emiel@vanseveren.dev>"]

[dependencies]
itertools = "0.10.5"
anyhow = "1.0.66"
regex = "1.7.0"
fixedbitset = "0.4.2"
ndarray = "0.15.6"
