[package]
name = "adventofcode2021"
version = "0.1.0"
edition = "2018"
author="Emiel Van Severen"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
